   GRANT SELECT ON SHFDA.TB_BOT_ACTION TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.TB_BOT_ACTION TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.TB_BOT_ACTION FOR SHFDA.TB_BOT_ACTION; 

   GRANT SELECT ON SHFDA.tb_bot_action_deploy TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_action_deploy TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_action_deploy FOR SHFDA.tb_bot_action_deploy; 
   
   GRANT SELECT ON SHFDA.tb_bot_block TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_block TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_block FOR SHFDA.tb_bot_block;  
   
   GRANT SELECT ON SHFDA.tb_bot_block_condition TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_block_condition TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_block_condition FOR SHFDA.tb_bot_block_condition;       
   
   GRANT SELECT ON SHFDA.tb_bot_block_deploy TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_block_deploy TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_block_deploy FOR SHFDA.tb_bot_block_deploy;       
   
   GRANT SELECT ON SHFDA.tb_bot_keyword TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_keyword TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_keyword FOR SHFDA.tb_bot_keyword;        
   
   GRANT SELECT ON SHFDA.tb_bot_scenario TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_scenario TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_scenario FOR SHFDA.tb_bot_scenario;    
      
   GRANT SELECT ON SHFDA.tb_bot_session TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_session TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_session FOR SHFDA.tb_bot_session; 
   
   GRANT SELECT ON SHFDA.tb_bot_set TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_set TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_set FOR SHFDA.tb_bot_set;    
   
   GRANT SELECT ON SHFDA.tb_bot_skill TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_skill TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_skill FOR SHFDA.tb_bot_skill;      
   
   GRANT SELECT ON SHFDA.tb_bot_skill_condition TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_skill_condition TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_skill_condition FOR SHFDA.tb_bot_skill_condition;     
   
   GRANT SELECT ON SHFDA.tb_bot_skill_condition_property TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_skill_condition_property TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_skill_condition_property FOR SHFDA.tb_bot_skill_condition_property;    
   
   GRANT SELECT ON SHFDA.tb_bot_skill_property TO RS_HFDA;
   GRANT SELECT,DELETE,UPDATE,INSERT ON SHFDA.tb_bot_skill_property TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.tb_bot_skill_property FOR SHFDA.tb_bot_skill_property;     
commit;


   GRANT SELECT ON SHFDA.SEQ_BOT_ACTION TO RS_HFDA;
   GRANT SELECT,ALTER ON SHFDA.SEQ_BOT_ACTION TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.SEQ_BOT_ACTION FOR SHFDA.SEQ_BOT_ACTION; 
   
   GRANT SELECT ON SHFDA.SEQ_BOT_BLOCK TO RS_HFDA;
   GRANT SELECT,ALTER ON SHFDA.SEQ_BOT_BLOCK TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.SEQ_BOT_BLOCK FOR SHFDA.SEQ_BOT_BLOCK; 
   
   GRANT SELECT ON SHFDA.SEQ_BOT_BLOCK_CONDITION TO RS_HFDA;
   GRANT SELECT,ALTER ON SHFDA.SEQ_BOT_BLOCK_CONDITION TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.SEQ_BOT_BLOCK_CONDITION FOR SHFDA.SEQ_BOT_BLOCK_CONDITION; 
   
   GRANT SELECT ON SHFDA.SEQ_BOT_CONDITION_KEY TO RS_HFDA;
   GRANT SELECT,ALTER ON SHFDA.SEQ_BOT_CONDITION_KEY TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.SEQ_BOT_CONDITION_KEY FOR SHFDA.SEQ_BOT_CONDITION_KEY; 
   
   GRANT SELECT ON SHFDA.SEQ_BOT_CONDITION_VALUE TO RS_HFDA;
   GRANT SELECT,ALTER ON SHFDA.SEQ_BOT_CONDITION_VALUE TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.SEQ_BOT_CONDITION_VALUE FOR SHFDA.SEQ_BOT_CONDITION_VALUE;    
   
   GRANT SELECT ON SHFDA.SEQ_BOT_KEYWORD TO RS_HFDA;
   GRANT SELECT,ALTER ON SHFDA.SEQ_BOT_KEYWORD TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.SEQ_BOT_KEYWORD FOR SHFDA.SEQ_BOT_KEYWORD; 
   
   GRANT SELECT ON SHFDA.SEQ_BOT_SCENARIO TO RS_HFDA;
   GRANT SELECT,ALTER ON SHFDA.SEQ_BOT_SCENARIO TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.SEQ_BOT_SCENARIO FOR SHFDA.SEQ_BOT_SCENARIO; 
   
   GRANT SELECT ON SHFDA.SEQ_BOT_SKILL TO RS_HFDA;
   GRANT SELECT,ALTER ON SHFDA.SEQ_BOT_SKILL TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.SEQ_BOT_SKILL FOR SHFDA.SEQ_BOT_SKILL; 
   
   
   GRANT SELECT ON SHFDA.SEQ_BOT_SKILL_CONDITION_PROPERTY TO RS_HFDA;
   GRANT SELECT,ALTER ON SHFDA.SEQ_BOT_SKILL_CONDITION_PROPERTY TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.SEQ_BOT_SKILL_CONDITION_PROPERTY FOR SHFDA.SEQ_BOT_SKILL_CONDITION_PROPERTY; 
   
   
   GRANT SELECT ON SHFDA.SEQ_BOT_SKILL_PROPERTY TO RS_HFDA;
   GRANT SELECT,ALTER ON SHFDA.SEQ_BOT_SKILL_PROPERTY TO RA_HFDA;
   CREATE SYNONYM PHFDAAPP.SEQ_BOT_SKILL_PROPERTY FOR SHFDA.SEQ_BOT_SKILL_PROPERTY; 

    commit;